export function createInitialState() {
  return {
    argument: "",
    sessionId: "",
    roommateLine: "",
    photoUrl: "",
    photoDataUrl: "",
    round: 1,
    player: 100,
    boss: 100,
    knocked: false,
    exchange: 0,
    evidence: 4,
    aggro: 3,
    conversationMode: "turn-style",
    voiceStyleId: "deeply-inconvenienced",
    lastFightCard: null,
    sentimentDuel: null,
    voice: {
      active: false,
      mode: "idle",
      sttMode: "",
      sttModel: "",
      stream: null,
      recorder: null,
      socket: null,
      recognizer: null,
      finalTranscript: "",
      interimTranscript: "",
      processing: false,
      lastConfidence: null,
      lastAdvancedTurnIndex: -1,
      endTurnTimer: 0,
      timing: {
        micStartAt: 0,
        firstTranscriptAt: 0,
        endOfTurnAt: 0,
        endOfTurnPending: false,
      },
    },
    tts: {
      audio: null,
      objectUrl: "",
      speaking: false,
      resolveSpeaking: null,
      watchdogTimer: 0,
    },
    frames: {
      closed: null,
      open: null,
    },
    talkAnim: null,
    agent: {
      audioContext: null,
      source: null,
      processor: null,
      outputCursor: 0,
      outputSources: new Set(),
      playing: false,
      lastUserText: "",
      lastAssistantText: "",
      scoring: false,
      keepAliveTimer: 0,
    },
  };
}
